build-job:
  stage: build
  image: rust:1.82
  variables:
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - .cargo/bin/
      - .cargo/registry/index/
      - .cargo/registry/cache/
      - target/
  script:
    - cargo build --release --verbose
  artifacts:
    paths:
      - target/release/discord_bot_ai