name: Building project
on:
  push:
    branches: [ "main", "dev", "windows-ci" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set lib postgres to PATH
      if: runner.os == 'Windows'
      run: |
        "$env:PGBIN" | Out-File -FilePath $env:GITHUB_PATH -Append
    - name: Build
      run: cargo build --release --verbose
    - name: Listing
      run: ls
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: discord_llm_ai-${{ matrix.os }}-${{ github.sha }}
        path: ./target/release/discord_bot_ai
        compression-level: 0