name: Building project on Linux
on:
  push:
    branches: [ "main", "dev", "windows-ci-test" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: ./.github/workflows/cargo-cache.yml
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --verbose
