name: Building project
on:
  push:
    branches: [ "main", "dev", "windows-ci-test" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{matrix.runner}}
    strategy:
      matrix:
        runner: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
